default_stages: [ commit, manual ]
default_language_version:
  node: 16.17.0
  python: python3.11
repos:
  - repo: "https://github.com/asottile/setup-cfg-fmt"
    rev: v2.2.0
    hooks:
      - id: setup-cfg-fmt
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: name-tests-test
        args:
          - "--django"
        exclude: "(factories/|_factory.py$)"
      - id: requirements-txt-fixer
      - id: check-symlinks
      - id: check-docstring-first
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: check-added-large-files
      - id: check-builtin-literals
        args:
          - "--ignore=dict,list"
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: django-migrations
        name: Check django migrations
        entry: python src/manage.py makemigrations --noinput --dry-run
        language: system
        types: [ python ]
        pass_filenames: false
        require_serial: true

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [ --all ]
        exclude: "(settings/|const(.*)/|__init__.py$|const(.*).py$|apps.py)"

  - repo: "https://github.com/pycqa/isort"
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args:
          - "--settings-file=pyproject.toml"
        # IMPORTANT: Excluded these folders/files to prevent cross/missing import.
        exclude: "(settings/|const(.*)/|__init__.py$|const(.*).py$|apps.py)"

  - repo: "https://github.com/psf/black"
    rev: 22.10.0
    hooks:
      - id: black

  - repo: "https://github.com/asottile/blacken-docs"
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==v21.5b1
        entry: blacken-docs --skip-errors

  - repo: "https://github.com/PyCQA/flake8"
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
          - >-
            --ignore=
              B001,B006,
              C901,
              E121,E126,E127,E128,E131,E203,E226,E251,E261,E262,E265,E401,E402,E501,E502,E722,
              F401,F401,F403,F403,F405,F405,F541,F541,
              N801,N802,N803,N806,N812,N814,N814,
              SIM102,SIM105,SIM106,SIM110,SIM118,SIM210,SIM300,
              T001,
              W292,W292,W391,W503,W503,W504,W504,
              TYP001, TYP002
          - "--max-line-length=120"
          - "--max-complexity=30"
          # - '--select=B,C,E,F,W,T4,B9'
        additional_dependencies:
          - pep8-naming
          - flake8-typing-imports==1.10.1
          - flake8-bugbear
          - flake8-mutable
          - flake8-print
          - flake8-simplify

  - repo: "https://github.com/asottile/pyupgrade"
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args:
          - "--py36-plus"

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [ python ]
        additional_dependencies:
          - pyright

  - repo: https://github.com/pycqa/pylint
    rev: v2.17.3
    hooks:
      - id: pylint
        args:
          - "--disable=all"
          - "--enable=E1124,E1132,E1125,E1120,E1121,E1123,W1113"
          - "--score=n"

  - repo: "https://github.com/PyCQA/bandit"
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          - "-lll"
          - "-iii"
          - "--skip=B105,B110,B311,B608"
          - "--quiet"
        exclude: "(migrations/|docs/|templates/|geo/|sent_emails/)"

  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.6.7
    hooks:
      - id: conventional-commits
