version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env_docker_mysql
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - indices.breaker.total.limit=20%


    networks:
      - ek-net
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    networks:
      - ek-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  my-db:
  certs:

networks:
  app-network:
  ek-net:
    driver: bridge
