version: '3'

services:
  mysql:
    restart: always
    image: 'mysql:8.0.28'
    container_name: mysql_8
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    volumes:
      - ./mysql:/etc/mysql/conf.d
      - ./mysqldump/:/docker-entrypoint-initdb.d/
      - mysql-8-data:/var/lib/mysql

  redis:
    restart: always
    image: redis
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
  elasticsearch:
    restart: always
    image: 'elasticsearch:7.10.1'
    container_name: elasticsearch
    ports:
      - "${ES_PORT}:9200"
    environment:
      - "discovery.type=single-node"
      - 'transport.tcp.port=${ES_PORT}'
      - http.port=9200
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=*
      - http.cors.enabled=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  mysql-8-data:
  redis-data:
  elasticsearch-data:
