# Generated by Django 5.1.1 on 2024-10-15 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_customuser_is_staff_customuser_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"ordering": ["-date_joined"]},
        ),
    ]
