from .bulk_import_product_view import BulkImportProductView
from .product_detail_view import ProductRetrieveUpdateDestroyView
from .product_es_search_view import ProductESSearchView
from .product_find_similars import SimilarProductView
from .product_list_create_view import ProductListCreateView
from .views import *
