# Generated by Django 5.1.1 on 2024-10-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_category_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at", "-updated_at", "name"]},
        ),
    ]
