# Generated by Django 5.1.2 on 2024-10-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_squashed_0006_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
